# Generated by Django 3.2.20 on 2023-07-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.PositiveBigIntegerField()),
                ('call_status', models.BooleanField(default=False)),
                ('captions', models.CharField(blank=True, max_length=255, null=True)),
                ('generate_time', models.DateTimeField(auto_now_add=True)),
                ('call_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
